import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export function MainContent() {
    return (_jsxs("main", { className: "flex-1 flex flex-col", children: [_jsx("header", { className: "h-14 px-4 flex items-center border-b border-gray-700", children: _jsx("h2", { className: "text-lg font-semibold", children: "# general" }) }), _jsx("div", { className: "flex-1 overflow-y-auto p-4", children: _jsxs("div", { className: "space-y-4", children: [_jsx(MessageCard, { type: "PLAN", sender: "PM", summary: "Project kickoff plan", body: "We will start by researching the market, then create marketing copy, and finally implement the landing page.", timestamp: "10:30 AM" }), _jsx(MessageCard, { type: "PROPOSAL", sender: "Research", summary: "Market research findings", body: "Based on initial research, the target market shows strong demand for AI orchestration tools. Key competitors include...", timestamp: "11:45 AM", artifacts: [{ path: 'research/market-analysis.md', hash: 'abc123' }] })] }) }), _jsx("div", { className: "p-4 border-t border-gray-700", children: _jsx("div", { className: "bg-gray-800 rounded-lg p-3", children: _jsx("p", { className: "text-gray-400 text-sm", children: "Agent messages will appear here. Tasks can be created from the sidebar." }) }) })] }));
}
const typeColors = {
    PLAN: 'bg-blue-600',
    PROPOSAL: 'bg-purple-600',
    EXEC_REPORT: 'bg-green-600',
    REVIEW: 'bg-yellow-600',
    BLOCKER: 'bg-red-600',
};
function MessageCard({ type, sender, summary, body, timestamp, artifacts }) {
    return (_jsx("div", { className: "bg-gray-800 rounded-lg p-4", children: _jsxs("div", { className: "flex items-start gap-3", children: [_jsx("div", { className: "w-10 h-10 rounded bg-gray-700 flex items-center justify-center flex-shrink-0", children: _jsx("span", { className: "text-sm font-medium", children: sender[0] }) }), _jsxs("div", { className: "flex-1 min-w-0", children: [_jsxs("div", { className: "flex items-center gap-2 mb-1", children: [_jsx("span", { className: "font-semibold", children: sender }), _jsx("span", { className: `px-2 py-0.5 rounded text-xs ${typeColors[type]}`, children: type }), _jsx("span", { className: "text-xs text-gray-400", children: timestamp })] }), _jsx("h3", { className: "font-medium mb-2", children: summary }), _jsx("p", { className: "text-gray-300 text-sm", children: body }), artifacts && artifacts.length > 0 && (_jsxs("div", { className: "mt-3 pt-3 border-t border-gray-700", children: [_jsx("p", { className: "text-xs text-gray-400 mb-1", children: "Artifacts:" }), _jsx("ul", { className: "space-y-1", children: artifacts.map((artifact) => (_jsxs("li", { className: "text-sm text-blue-400", children: [artifact.path, _jsxs("span", { className: "text-gray-500 ml-2", children: ["(", artifact.hash.slice(0, 7), ")"] })] }, artifact.path))) })] }))] })] }) }));
}
//# sourceMappingURL=MainContent.js.map