import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { clsx } from 'clsx';
const channels = [
    { id: 'general', name: 'general', type: 'department' },
    { id: 'research', name: 'research', type: 'department' },
    { id: 'dev', name: 'dev', type: 'department' },
];
export function Sidebar() {
    return (_jsxs("aside", { className: "w-64 bg-sidebar flex flex-col border-r border-gray-700", children: [_jsxs("div", { className: "p-4 border-b border-gray-700", children: [_jsx("h1", { className: "text-xl font-bold", children: "Clutch" }), _jsx("p", { className: "text-sm text-gray-400", children: "AI Agent Organization" })] }), _jsxs("nav", { className: "flex-1 overflow-y-auto p-2", children: [_jsxs("div", { className: "mb-4", children: [_jsx("h2", { className: "px-2 py-1 text-xs font-semibold text-gray-400 uppercase", children: "Channels" }), _jsx("ul", { className: "space-y-0.5", children: channels.map((channel) => (_jsx("li", { children: _jsxs("button", { className: clsx('w-full px-2 py-1 text-left rounded hover:bg-sidebar-hover', 'flex items-center gap-2 text-gray-300'), children: [_jsx("span", { className: "text-gray-500", children: "#" }), channel.name] }) }, channel.id))) })] }), _jsxs("div", { className: "mb-4", children: [_jsx("h2", { className: "px-2 py-1 text-xs font-semibold text-gray-400 uppercase", children: "Agents" }), _jsxs("ul", { className: "space-y-0.5", children: [_jsx("li", { children: _jsxs("button", { className: "w-full px-2 py-1 text-left rounded hover:bg-sidebar-hover flex items-center gap-2 text-gray-300", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-green-500" }), "PM"] }) }), _jsx("li", { children: _jsxs("button", { className: "w-full px-2 py-1 text-left rounded hover:bg-sidebar-hover flex items-center gap-2 text-gray-300", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-green-500" }), "Research"] }) }), _jsx("li", { children: _jsxs("button", { className: "w-full px-2 py-1 text-left rounded hover:bg-sidebar-hover flex items-center gap-2 text-gray-300", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-yellow-500" }), "Developer"] }) }), _jsx("li", { children: _jsxs("button", { className: "w-full px-2 py-1 text-left rounded hover:bg-sidebar-hover flex items-center gap-2 text-gray-300", children: [_jsx("span", { className: "w-2 h-2 rounded-full bg-gray-500" }), "Marketing"] }) })] })] })] }), _jsx("div", { className: "p-4 border-t border-gray-700", children: _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "w-8 h-8 rounded bg-blue-600 flex items-center justify-center", children: _jsx("span", { className: "text-sm font-medium", children: "O" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium", children: "Organization" }), _jsx("p", { className: "text-xs text-gray-400", children: "4 agents active" })] })] }) })] }));
}
//# sourceMappingURL=Sidebar.js.map